#define DEFAULT_SERVER_PORT 5192 // port to recv cmd and send cmd execution results

#define MAX_NUM_PENDING_CONNECTIONS 1024

#define MAX_NUM_SHARED_FILE_RECORDS 100
#define MAX_NUM_CONNECTED_CLIENTS 10
#define CLIENT_ID_PREFIX_STRING "client"

#define MAX_NUM_COMMAND_TOKENS 3
#define NO_MORE_CLIENTS_SHOULD_CONNECT -1
#define NO_MORE_FILES_SHOULD_BE_ADDED -1

#define FILE_RECORD_IN_USE 1
#define FILE_RECORD_VACANT 0
